name: check-action-info
author: Data Management and Analysis Program at the National Cancer Institute
description: See how things are passed

on:
  workflow_call:
    inputs:
      container:  # id of input
        description: 'The link to the docker image to use.'
        required: false
        default: 'ubuntu:latest'
      action:
        description: 'What action to run? ["test", post-merge", "unit-test-on-changed", "all-unit-tests", "check"]'
        required: false
        default: 'test'
      saysomthing:
        deccription: 'Customed information for testing'
        required: false
        default: 'Test test'
      githubtoken:
        deccription: 'githubtoken'
        required: true
      githubbranch:
        deccription: 'githubbranch'
        required: true
    
jobs:
  Routine_Check_for_Commit:
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
      steps:
        - run: echo "Running test in DSPWorkflow container"
        
        - uses: actions/checkout@v3
          with:
             token: ${{ inputs.githubtoken }}
             ref: ${{ inputs.githubbranch }}
             fetch-depth: 0
        
        id: extract_branch
        - name: Test test
          run: |
            echo "${inputs.container}"
            echo "${inputs.githubbranch}"
    
        - name: Check spelling
          if: ${{ inputs.action == 'test' }}
          run: |
            echo "run test"
            echo "${inputs.saysomthing}"