name: check-action-info

on:
  workflow_call:
    inputs:
      image_to_use:
        required: false
        default: 'ubuntu:latest'
        type: string
        
      action:
        required: false
        default: 'test'
        type: string
        
      saysomthing:
        required: false
        default: 'Test test'
        type: string
        
      githubbranch:
        required: true
        type: string
    
jobs:
  Routine_Check_for_Commit:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_to_use }}
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo "Running test in DSPWorkflow container"s
      
      - uses: actions/checkout@v3
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
           ref: "${{ inputs.githubbranch }}"
           fetch-depth: 0
           
      - name: Test test
        run: |
          echo "${{ inputs.container }}"
          echo "${{ inputs.githubbranch }}"
          echo "${GITHUB_REPOSITORY}"
          pwd
          git clone https://github.com/ruiheesi/check-action-info.git
          cp ./check-action-info/test.log .
          cat test.log
  
      - name: Check spelling
        if: ${{ inputs.action == 'test' }}
        run: |
          echo "run test"
          echo "${{ inputs.saysomthing }}"