name: check-action-info

on:
  workflow_call:
    inputs:
      container:
        description: 'The link to the docker image to use.'
        required: false
        default: 'ubuntu:latest'
        type: string
      action:
        description: 'What action to run? ["test", post-merge", "unit-test-on-changed", "all-unit-tests", "check"]'
        required: false
        default: 'test'
        type: string
      saysomthing:
        deccription: 'Customed information for testing'
        required: false
        default: 'Test test'
        type: string
      githubtoken:
        deccription: 'githubtoken'
        required: true
        type: string
      githubbranch:
        deccription: 'githubbranch'
        required: true
        type: string
    
jobs:
  Routine_Check_for_Commit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running test in DSPWorkflow container"
      
      - name: Test test
        run: |
          echo "${inputs.container}"
          echo "${inputs.githubbranch}"
      
      - uses: actions/checkout@v3
        with:
           token: "${inputs.githubtoken}"
           ref: "${inputs.githubbranch}"
           fetch-depth: 0
       
      - name: input action
        shell: bash
        run: |
          echo "##[set-output name=action;]$(echo ${inputs.action})"
        id: extract_action
  
      - name: Check spelling
        run: |
          echo "run test"
          echo "${inputs.saysomthing}"