name: check-action-info

on:
  workflow_call:
    inputs:
      container:
        required: false
        default: 'ubuntu:latest'
        type: string
        
      action:
        required: false
        default: 'test'
        type: string
        
      saysomthing:
        required: false
        default: 'Test test'
        type: string
        
      githubtoken:
        required: true
        type: string
        
      githubbranch:
        required: true
        type: string
    
jobs:
  Routine_Check_for_Commit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running test in DSPWorkflow container"
      
      - name: Test test
        run: |
          echo "${inputs.container}"
          echo "${inputs.githubbranch}"
      
      - uses: actions/checkout@v3
        with:
           token: "${inputs.githubtoken}"
           ref: "${inputs.githubbranch}"
           fetch-depth: 0
       
      - name: input action
        shell: bash
        run: |
          echo "##[set-output name=action;]$(echo ${inputs.action})"
        id: extract_action
  
      - name: Check spelling
        run: |
          echo "run test"
          echo "${inputs.saysomthing}"